# Position.msg

# ROS header
Header header

# For ublox raw-data
float64 ublox_lat
float64 ublox_lon
float64 ublox_alt
float64 ublox_east
float64 ublox_north
float64 ublox_up

# For imu 
float64 imu_lat
float64 imu_lon
float64 imu_alt
float64 imu_east
float64 imu_north
float64 imu_up


# For ndt 
float64 ndt_lat
float64 ndt_lon
float64 ndt_alt
float64 ndt_east
float64 ndt_north
float64 ndt_up

# For novatel
float64 nov_lat
float64 nov_lon
float64 nov_alt
float64 nov_east
float64 nov_north
float64 nov_up


# For the result for proposed method
float64 msf_lat
float64 msf_lon
float64 msf_alt
float64 msf_east
float64 msf_north
float64 msf_up



# GNSS status
float64 gnss_indicators
